name: "Hello Actions"
description: "Greet Me"
author: "octocat@github.com"

inputs:
  INPUT_MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "mic"
  color: "purple"
